In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

2024-06-18 10:03:57.719739: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-18 10:03:57.719958: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-18 10:03:57.891427: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


# Tensors

## constant

In [2]:
tf.constant(True,dtype=bool)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [3]:
tf.constant([1,2,3,4])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [4]:
tf.constant([[1,2,3],[4,5,6]],dtype=tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [5]:
arr=tf.constant([[[1.0,2,3],[4,5,6]],[[1,2,3],[5,6,7]]])

## shape

In [6]:
arr.shape

TensorShape([2, 2, 3])

## ndim

In [7]:
arr.ndim

3

## dtype

In [8]:
arr.dtype

tf.float32

In [9]:
tf.constant('Hello World',dtype=tf.string)

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

# Casting

In [10]:
arr=tf.constant([[1.09,-2.00,3],[4,5,6]],dtype=tf.float32)

In [11]:
arr

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.09, -2.  ,  3.  ],
       [ 4.  ,  5.  ,  6.  ]], dtype=float32)>

## Cast keyword

In [12]:
tf.cast(arr,dtype=tf.float64)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.09000003, -2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ]])>

In [13]:
tf.cast(arr,dtype=tf.uint8)

<tf.Tensor: shape=(2, 3), dtype=uint8, numpy=
array([[  1, 254,   3],
       [  4,   5,   6]], dtype=uint8)>

# Initialization

In [14]:
np_array=np.array([1,2,3,4])
python_list=[[1,2,3,4],[4,5,6,7]]

## convert_to_tensor

In [15]:
tf.convert_to_tensor(np_array)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [16]:
tf.convert_to_tensor(python_list,dtype=tf.float16)

<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]], dtype=float16)>

## eye

In [17]:
tf.eye(4) # or tf.eye(4,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [18]:
tf.eye(3,4,batch_shape=[3])

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]],

       [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]],

       [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)>

## fill

In [19]:
tf.fill((3,3),value=10)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]], dtype=int32)>

## zeros

In [20]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## ones

In [21]:
tf.ones((3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

## random_normal_initializer

In [22]:
initializer=tf.random_normal_initializer(mean=0,stddev=1,seed=45)

In [23]:
initializer

In [24]:
initializer(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.4053881 ,  1.460551  ,  0.62129664],
       [-0.6539117 ,  1.2385781 , -0.28060445],
       [ 0.4289684 ,  0.1587181 , -0.875791  ]], dtype=float32)>

## range

In [25]:
tf.range(start=1,limit=10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [26]:
arr=tf.eye(3,5)

In [27]:
print(tf.shape(arr))

tf.Tensor([3 5], shape=(2,), dtype=int32)


## size

In [28]:
print(tf.size(arr))

tf.Tensor(15, shape=(), dtype=int32)


# Random Module

## random.normal

In [29]:
tf.random.normal(shape=(3,4),mean=0,stddev=1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.14995909,  0.09866119,  0.12286568,  0.550274  ],
       [ 0.40145504, -0.67026085, -1.0261133 ,  0.08085784],
       [-0.715018  ,  1.4231852 ,  0.6164207 , -1.2227035 ]],
      dtype=float32)>

## random.uniform

In [30]:
tf.random.uniform(shape=(5,6),minval=0,maxval=2)

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0.3012035 , 0.07725024, 0.7872014 , 1.7629213 , 0.4857993 ,
        0.7042439 ],
       [1.8625498 , 1.458878  , 1.3543749 , 1.5084138 , 0.72621346,
        1.1090219 ],
       [1.918678  , 1.194459  , 1.0927854 , 1.8093603 , 1.9302797 ,
        0.02757812],
       [1.8616278 , 0.7789135 , 1.9610956 , 0.6639886 , 0.4219184 ,
        0.6806474 ],
       [0.1405549 , 1.3877633 , 0.29506326, 0.49907398, 0.4389577 ,
        1.8687975 ]], dtype=float32)>

# Math

## abs

In [31]:
print(tf.abs(-1))

tf.Tensor(1, shape=(), dtype=int32)


In [32]:
value=[56+78j]

In [33]:
tf.abs(value)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([96.02083107])>

## sqrt

In [34]:
tf.sqrt(((56.0)**2)+((78.0)**2)) #tf.sqrt support only the float

<tf.Tensor: shape=(), dtype=float32, numpy=96.02083>

## sin

In [35]:
tf.sin(22/7)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.0012644208>

## add,subtract,multiply,divide

In [36]:
def four_operation(value1,value2):
    add=tf.add(value1,value2)
    sub=tf.subtract(value1,value2)
    mul=tf.multiply(value1,value2)
    div=tf.divide(value1,value2)
    return [add,sub,mul,div]

In [37]:
for i in four_operation([3,4],[3]):
    print(i)

tf.Tensor([6 7], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([ 9 12], shape=(2,), dtype=int32)
tf.Tensor([1.         1.33333333], shape=(2,), dtype=float64)


## Divide no nan

In [38]:
tf.math.divide_no_nan(3,0)

<tf.Tensor: shape=(), dtype=float64, numpy=0.0>

In [39]:
tf.multiply([1,2,3,4],[[1],[2],[4]]) # element wise multiplication 

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 4,  8, 12, 16]], dtype=int32)>

## argmax

In [40]:
np.argmax([3,4,5])

2

In [41]:
tf.argmax([3,4,5])

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [42]:
np.max([2,3])

3

## tf.maximum

In [43]:
tf.maximum(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## tf.cumsum

In [44]:
tf.cumsum([1,2,3,4])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  3,  6, 10], dtype=int32)>

In [45]:
np.cumsum([3,4,5,6])

array([ 3,  7, 12, 18])

In [46]:
all(np.array([3,4])==np.array([3,4]))

True

## tf.equal

In [47]:
tf.equal([3,4],[3,4])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [48]:
np.power(2,4)

16

## tf.pow

In [49]:
tf.pow(2,4)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

## tf.reduce_sum

In [50]:
tf.reduce_sum([2,3,4,5])

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [51]:
arr1=pd.Series([2,3,4,5,5])

In [52]:
arr1.nlargest(2)

3    5
4    5
dtype: int64

In [53]:
arr2=[[1,2,3],
      [6,7,8],
      [6,9,10]]

## tf.reduce_mean with different axis variations

In [54]:
print(tf.reduce_mean(arr2))
print(tf.reduce_mean(arr2,axis=0))
print(tf.reduce_mean(arr2,axis=1))# Likewise reduce by sum,std etc

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([4 6 7], shape=(3,), dtype=int32)
tf.Tensor([2 7 8], shape=(3,), dtype=int32)


## tf.math.top_k

In [55]:
tf.math.top_k(arr2)# default k=1

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 3],
       [ 8],
       [10]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2]], dtype=int32)>)

In [56]:
tf.math.top_k(arr2,k=2) #1-value,2-position

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  2],
       [ 8,  7],
       [10,  9]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

# Linear Algebra

In [57]:
arr1=tf.constant([[1,2,3,4],[4,5,6,7]],dtype=tf.float16)
arr2=tf.constant([[1,2],[3,4],[5,6],[7,8]],dtype=tf.float16)

In [58]:
arr1.shape

TensorShape([2, 4])

In [59]:
arr2.shape

TensorShape([4, 2])

## tf.linalg.matmul

In [60]:
output=tf.linalg.matmul(arr1,arr2) # matrix multiplication is different from element multiplication

In [61]:
output.shape

TensorShape([2, 2])

## Matrix multiplication with symbol

In [62]:
  arr1@arr2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 50.,  60.],
       [ 98., 120.]], dtype=float16)>

## tf.transpose

In [63]:
tf.transpose(arr1)

<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.],
       [4., 7.]], dtype=float16)>

## tf.linalg.adjoint

In [64]:
tf.linalg.adjoint(arr2)

<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[1., 3., 5., 7.],
       [2., 4., 6., 8.]], dtype=float16)>

## tf.linalg.inv

In [65]:
tf.linalg.inv([[1.0,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

## tf.linalg.det

In [66]:
tf.linalg.det([[1.0,2],[3,4]])

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

# Einsum

In [67]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[1,2,3,4],[5,6,7,8]])

In [68]:
arr2.shape

(2, 4)

In [69]:
arr1.shape

(2, 4)

In [70]:
np.einsum('ij,ij->ij',arr1,arr2)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [71]:
np.einsum('ij,ik->kj',arr1,arr2)

array([[26, 32, 38, 44],
       [32, 40, 48, 56],
       [38, 48, 58, 68],
       [44, 56, 68, 80]])

In [72]:
arr1=np.random.randint(1,100,size=(2,3,4))

In [73]:
arr2=np.random.randint(1,100,size=(2,4,3))

In [74]:
tf.einsum('lij,ljk->lik',arr1,arr2)

<tf.Tensor: shape=(2, 3, 3), dtype=int64, numpy=
array([[[ 4489,  3258,  3631],
        [ 4099,  3738,  3672],
        [ 5105,  4741,  6608]],

       [[ 3855,  5794,  6385],
        [13656,  6452, 15865],
        [13567,  7623, 16570]]])>

In [75]:
tf.linalg.matmul(arr1,arr2)

<tf.Tensor: shape=(2, 3, 3), dtype=int64, numpy=
array([[[ 4489,  3258,  3631],
        [ 4099,  3738,  3672],
        [ 5105,  4741,  6608]],

       [[ 3855,  5794,  6385],
        [13656,  6452, 15865],
        [13567,  7623, 16570]]])>

In [76]:
tf.einsum('lij->',arr1)

<tf.Tensor: shape=(), dtype=int64, numpy=946>

In [77]:
np.sum(arr1)

946

In [78]:
print('Tensorflow Einsum : ',tf.einsum('lij->ij',arr1))
print('Numpy axis sum : ',np.sum(arr1,axis=0))

Tensorflow Einsum :  tf.Tensor(
[[160   7  50  45]
 [ 72  99  46 105]
 [ 80 123  56 103]], shape=(3, 4), dtype=int64)
Numpy axis sum :  [[160   7  50  45]
 [ 72  99  46 105]
 [ 80 123  56 103]]


In [79]:
arr1=tf.constant([[1,2,3],[5,6,7]])

In [80]:
print('Tensorflow Einsum : ',tf.einsum('ij->i',arr1))
print('Numpy axis sum : ',np.sum(arr1,axis=1))

Tensorflow Einsum :  tf.Tensor([ 6 18], shape=(2,), dtype=int32)
Numpy axis sum :  [ 6 18]


### Expand Dims Function

In [81]:
## Expand Tensor by one dimension

In [82]:
print('Axis=-1 : ',tf.expand_dims(arr1,axis=-1))
print('Axis=0 : ',tf.expand_dims(arr1,axis=0))
print('Axis=1 : ',tf.expand_dims(arr1,axis=1))
print('Axis=2 : ',tf.expand_dims(arr1,axis=2))

Axis=-1 :  tf.Tensor(
[[[1]
  [2]
  [3]]

 [[5]
  [6]
  [7]]], shape=(2, 3, 1), dtype=int32)
Axis=0 :  tf.Tensor(
[[[1 2 3]
  [5 6 7]]], shape=(1, 2, 3), dtype=int32)
Axis=1 :  tf.Tensor(
[[[1 2 3]]

 [[5 6 7]]], shape=(2, 1, 3), dtype=int32)
Axis=2 :  tf.Tensor(
[[[1]
  [2]
  [3]]

 [[5]
  [6]
  [7]]], shape=(2, 3, 1), dtype=int32)


### Squeeze function

In [83]:
arr1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>

In [84]:
#Squeeze reduce by 1 dim so the value must be 1. ex : (1,2,3,4) axis =0 works here

In [85]:
tf.squeeze(tf.expand_dims(arr1,axis=0),axis=0) # we can convert the expand dims array to normal by squeeze function

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>

### reshape

In [86]:
tf.reshape(arr1,shape=(6,-1))

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [5],
       [6],
       [7]], dtype=int32)>

### Concat

In [87]:
def arr_initializer():
    arr1=np.random.randint(1,100,size=(3,4))
    arr2=np.random.randint(1,100,size=(3,4))
    arr1=tf.convert_to_tensor(arr1)
    arr2=tf.convert_to_tensor(arr2)
    return arr1,arr2

In [88]:
arr1,arr2=arr_initializer()

In [89]:
print(arr1.shape,'\n',arr2.shape)

(3, 4) 
 (3, 4)


In [90]:
tf.concat([arr1,arr2],axis=0)

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[46, 50, 68, 14],
       [17, 68, 64, 91],
       [79, 28,  4, 72],
       [64, 62, 32, 95],
       [76, 89,  4, 71],
       [52, 41, 58, 13]])>

In [91]:
tf.concat([arr1,arr2],axis=1)

<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
array([[46, 50, 68, 14, 64, 62, 32, 95],
       [17, 68, 64, 91, 76, 89,  4, 71],
       [79, 28,  4, 72, 52, 41, 58, 13]])>

### Stack

In [92]:
print(arr1.shape,'\n',arr2.shape)

(3, 4) 
 (3, 4)


In [93]:
tf.stack([arr1,arr2],axis=0) # create a new axis

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[46, 50, 68, 14],
        [17, 68, 64, 91],
        [79, 28,  4, 72]],

       [[64, 62, 32, 95],
        [76, 89,  4, 71],
        [52, 41, 58, 13]]])>

In [94]:
tf.stack([arr1,arr2],axis=1) # create a new axis

<tf.Tensor: shape=(3, 2, 4), dtype=int64, numpy=
array([[[46, 50, 68, 14],
        [64, 62, 32, 95]],

       [[17, 68, 64, 91],
        [76, 89,  4, 71]],

       [[79, 28,  4, 72],
        [52, 41, 58, 13]]])>

In [95]:
tf.stack([arr1,arr2],axis=2) # create a new axis

<tf.Tensor: shape=(3, 4, 2), dtype=int64, numpy=
array([[[46, 64],
        [50, 62],
        [68, 32],
        [14, 95]],

       [[17, 76],
        [68, 89],
        [64,  4],
        [91, 71]],

       [[79, 52],
        [28, 41],
        [ 4, 58],
        [72, 13]]])>

### Pad

In [96]:
arr2=[[1,1],# one row above ,one row below in output
      [2,2]] # Two column left and two column right in output

In [97]:
arr1

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[46, 50, 68, 14],
       [17, 68, 64, 91],
       [79, 28,  4, 72]])>

In [98]:
newarray=tf.pad(arr1,paddings=arr2,mode='CONSTANT',constant_values=0)

In [99]:
newarray

<tf.Tensor: shape=(5, 8), dtype=int64, numpy=
array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 46, 50, 68, 14,  0,  0],
       [ 0,  0, 17, 68, 64, 91,  0,  0],
       [ 0,  0, 79, 28,  4, 72,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])>

# Ragged Tensor

In [100]:
print("Ragged Tensor is for non rectangular matrices")

Ragged Tensor is for non rectangular matrices


## Ragged Tensor

In [101]:
tf.ragged.constant([[1,2,3],
                    [4,5],
                    [6]])

<tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>

## Ragged Tensor from row lengths

In [102]:
tf.RaggedTensor.from_row_lengths(
    values=[1,2,3,4,5,6,7,8,9],
    row_lengths=[3,0,2,0,4])

<tf.RaggedTensor [[1, 2, 3], [], [4, 5], [], [6, 7, 8, 9]]>

## Ragged Tensor from row limits

In [103]:
tf.RaggedTensor.from_row_limits(
    values=[1,2,3,4,5,6,7,8,9],
    row_limits=[4,7,9])

<tf.RaggedTensor [[1, 2, 3, 4], [5, 6, 7], [8, 9]]>

In [104]:
tf.RaggedTensor.from_row_splits(
    values=[1,2,3,4,5,6,7,8,9],
    row_splits=[0,4,7,9])

<tf.RaggedTensor [[1, 2, 3, 4], [5, 6, 7], [8, 9]]>

## Ragged Tensor from Tensor

In [105]:
arr1

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[46, 50, 68, 14],
       [17, 68, 64, 91],
       [79, 28,  4, 72]])>

In [106]:
tf.RaggedTensor.from_tensor(
    tensor=arr1,
    lengths=[2,3,4])

<tf.RaggedTensor [[46, 50], [17, 68, 64], [79, 28, 4, 72]]>

# SPARSE TENSOR (2 Functions)

- 1)SparseTensor 2)to_dense)

In [107]:
sparse_tensor=tf.sparse.SparseTensor(indices=[[1,1],[2,2]],values=[34,45],dense_shape=[3,3])
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[1 1]
 [2 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([34 45], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))

In [108]:
tf.sparse.to_dense(sparse_tensor) # dense Tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 0,  0,  0],
       [ 0, 34,  0],
       [ 0,  0, 45]], dtype=int32)>

# Variables

In [109]:
var1=tf.Variable([1,2,3])

## assign

In [110]:
var1.assign([3,4,8])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 4, 8], dtype=int32)>

In [111]:
var1

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([3, 4, 8], dtype=int32)>

## assign_add

In [112]:
var1.assign_add(delta=[2,3,4])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([ 5,  7, 12], dtype=int32)>

In [113]:
3+2,4+3,8+4

(5, 7, 12)

## assign_sub

In [114]:
var1.assign_sub([2,3,4])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 4, 8], dtype=int32)>